// AUTO-GENERATED by scripts/extract-content.mjs — do not edit by hand.
// Source of truth: ../../portfolio/index.html
export const hero = {
  "eyebrow": "Senior UI/UX Designer",
  "headingHtml": "Interface design for the <em>institutions</em> people put their trust in.",
  "lede": "I turn complex, multi-stakeholder, bilingual (Arabic / English) requirements into products that ministries, authorities, universities and enterprise clients can ship with confidence — five years of experience, most of it spent inside consultancies delivering directly for public-sector clients. Always open to a conversation about what you're building.",
  "trustLabel": "Engaged for government & enterprise work via",
  "trust": [
    {
      "name": "Mannai Corporation",
      "url": "https://mannai.com/"
    },
    {
      "name": "Saudi Azm",
      "url": "https://azm.com/"
    },
    {
      "name": "AZM X",
      "url": "https://azmx.sa/"
    }
  ],
  "mosaic": [
    {
      "href": "#/work/case-qnl",
      "tag": "Qatar National Library",
      "src": "assets/img/001.jpg",
      "alt": "Qatar National Library",
      "w": 480,
      "h": 1277
    },
    {
      "href": "#/work/case-saso",
      "tag": "SASO · Saudi Arabia",
      "src": "assets/img/002.jpg",
      "alt": "SASO · Saudi Arabia",
      "w": 480,
      "h": 507
    },
    {
      "href": "#/work/case-joodeskan",
      "tag": "Jood Eskan · GWR 2023",
      "src": "assets/img/003.jpg",
      "alt": "Jood Eskan · GWR 2023",
      "w": 480,
      "h": 1370
    },
    {
      "href": "#/work/case-gama",
      "tag": "General Authority for Minors' Affairs · Qatar",
      "src": "assets/img/004.jpg",
      "alt": "General Authority for Minors' Affairs · Qatar",
      "w": 480,
      "h": 674
    },
    {
      "href": "#/work/case-mecc",
      "tag": "MECC · Qatar",
      "src": "assets/img/005.jpg",
      "alt": "MECC · Qatar",
      "w": 480,
      "h": 900
    },
    {
      "href": "#/work/case-mehrab",
      "tag": "Mehrab · Charitable",
      "src": "assets/img/006.jpg",
      "alt": "Mehrab · Charitable",
      "w": 480,
      "h": 1378
    },
    {
      "href": "#/work/case-qu",
      "tag": "Qatar University",
      "src": "assets/img/007.jpg",
      "alt": "Qatar University",
      "w": 480,
      "h": 350
    },
    {
      "href": "#/work/case-grsia",
      "tag": "GRSIA · Daman",
      "src": "assets/img/008.jpg",
      "alt": "GRSIA · Daman",
      "w": 480,
      "h": 1038
    },
    {
      "href": "#/work/case-trags",
      "tag": "TRAGS · Qatar",
      "src": "assets/img/009.jpg",
      "alt": "TRAGS · Qatar",
      "w": 480,
      "h": 552
    },
    {
      "href": "#/work/case-mcit",
      "tag": "MCIT · Qatar",
      "src": "assets/img/010.jpg",
      "alt": "MCIT · Qatar",
      "w": 480,
      "h": 762
    },
    {
      "href": "#/work/case-joodeskan-kiosk",
      "tag": "Jood Eskan · Donation Kiosk",
      "src": "assets/img/011.jpg",
      "alt": "Jood Eskan · Donation Kiosk",
      "w": 480,
      "h": 175
    },
    {
      "href": "#/work/case-optimumvision",
      "tag": "Optimum Vision · Dubai",
      "src": "assets/img/012.jpg",
      "alt": "Optimum Vision · Dubai",
      "w": 480,
      "h": 340
    },
    {
      "href": "#/work/case-qpmc",
      "tag": "Al-Awalia (QPMC) · Qatar",
      "src": "assets/img/013.jpg",
      "alt": "Al-Awalia (QPMC) · Qatar",
      "w": 480,
      "h": 1648
    },
    {
      "href": "#/work/case-ccq",
      "tag": "Community College of Qatar",
      "src": "assets/img/014.jpg",
      "alt": "Community College of Qatar",
      "w": 480,
      "h": 526
    },
    {
      "href": "#/work/case-surah",
      "tag": "Surah App · Qur'an Study",
      "src": "assets/img/015.jpg",
      "alt": "Surah App · Qur'an Study",
      "w": 480,
      "h": 224
    },
    {
      "href": "#/work/case-manateq",
      "tag": "Manateq · Investor Finance",
      "src": "assets/img/016.png",
      "alt": "Manateq · Investor Finance",
      "w": 1280,
      "h": 1132
    },
    {
      "href": "#/work/case-qsl",
      "tag": "QSL · Club Compliance",
      "src": "assets/img/017.jpg",
      "alt": "QSL · Club Compliance",
      "w": 560,
      "h": 315
    },
    {
      "href": "#/work/case-clayton",
      "tag": "Clayton Art House · Craft Studio",
      "src": "assets/img/168.jpg",
      "alt": "Clayton Art House · Craft Studio",
      "w": 654,
      "h": 805
    }
  ]
} as const;
export const impact = {
  "eyebrow": "By the Numbers",
  "title": "Track Record",
  "body": "Five years, eight government institutions, and one Guinness World Record along the way.",
  "stats": [
    {
      "num": "18",
      "label": "Shipped products"
    },
    {
      "num": "8",
      "label": "Government & public-sector clients"
    },
    {
      "num": "2",
      "label": "Countries delivered in"
    },
    {
      "num": "2023",
      "label": "Guinness World Records recognition"
    }
  ]
} as const;
export const homeCta = {
  "title": "Hiring for a product team? Let's talk.",
  "body": "Government and enterprise product design, five years in — open to full-time roles and relocation, anywhere."
} as const;
export const workHead = {
  "eyebrow": "Selected Work",
  "title": "Case Studies",
  "body": "Eighteen shipped products across government, fintech, PropTech, enterprise and lifestyle — eight of them national institutions."
} as const;
export const workGroups = [
  {
    "label": "Government & Public Sector (08)",
    "cards": [
      {
        "title": "Qatar National Library",
        "tag": "Gov — Culture & Knowledge",
        "href": "#/work/case-qnl",
        "src": "assets/img/018.jpg",
        "alt": "Qatar National Library",
        "w": 480,
        "h": 1277
      },
      {
        "title": "General Authority for Minors' Affairs",
        "tag": "Gov — Public Authority",
        "href": "#/work/case-gama",
        "src": "assets/img/019.jpg",
        "alt": "General Authority for Minors' Affairs",
        "w": 480,
        "h": 674
      },
      {
        "title": "GRSIA (“Daman”)",
        "tag": "Gov — Retirement & Insurance",
        "href": "#/work/case-grsia",
        "src": "assets/img/020.jpg",
        "alt": "GRSIA (“Daman”)",
        "w": 480,
        "h": 1038
      },
      {
        "title": "Qatar University",
        "tag": "Gov — Higher Education",
        "href": "#/work/case-qu",
        "src": "assets/img/021.jpg",
        "alt": "Qatar University",
        "w": 480,
        "h": 350
      },
      {
        "title": "Saudi Standards, Metrology & Quality Org.",
        "tag": "Gov — Trade & Consumer Protection",
        "href": "#/work/case-saso",
        "src": "assets/img/022.jpg",
        "alt": "Saudi Standards, Metrology & Quality Org.",
        "w": 480,
        "h": 507
      },
      {
        "title": "MCIT, State of Qatar",
        "tag": "Gov — Digital Ministry",
        "href": "#/work/case-mcit",
        "src": "assets/img/023.jpg",
        "alt": "MCIT, State of Qatar",
        "w": 480,
        "h": 762
      },
      {
        "title": "Ministry of Environment & Climate Change, Qatar",
        "tag": "Gov — Environment & Climate",
        "href": "#/work/case-mecc",
        "src": "assets/img/024.jpg",
        "alt": "Ministry of Environment & Climate Change, Qatar",
        "w": 480,
        "h": 900
      },
      {
        "title": "Manateq",
        "tag": "Gov — Economic Zones & Investor Finance",
        "href": "#/work/case-manateq",
        "src": "assets/img/025.png",
        "alt": "Manateq Partners Portal — Budget dashboard",
        "w": 1280,
        "h": 1711
      }
    ]
  },
  {
    "label": "Flagship Achievements (02)",
    "cards": [
      {
        "title": "Jood Eskan — Ramadan Giving Campaign",
        "tag": "PropTech & Social Impact · Saudi Arabia",
        "href": "#/work/case-joodeskan",
        "src": "assets/img/026.jpg",
        "alt": "Jood Eskan — Ramadan Giving Campaign",
        "w": 480,
        "h": 1370
      },
      {
        "title": "Jood Eskan — Donation Kiosk",
        "tag": "Self-Service & Physical UX · Saudi Arabia",
        "href": "#/work/case-joodeskan-kiosk",
        "src": "assets/img/027.jpg",
        "alt": "Jood Eskan — Donation Kiosk",
        "w": 480,
        "h": 175
      }
    ]
  },
  {
    "label": "Featured Projects (08)",
    "cards": [
      {
        "title": "Optimum Vision",
        "tag": "Concierge & Travel · Dubai, UAE",
        "href": "#/work/case-optimumvision",
        "src": "assets/img/028.jpg",
        "alt": "Optimum Vision",
        "w": 480,
        "h": 340
      },
      {
        "title": "TRAGS",
        "tag": "Enterprise & EPC · Qatar",
        "href": "#/work/case-trags",
        "src": "assets/img/029.jpg",
        "alt": "TRAGS",
        "w": 480,
        "h": 552
      },
      {
        "title": "Mehrab",
        "tag": "Charitable & Social Impact · Saudi Arabia",
        "href": "#/work/case-mehrab",
        "src": "assets/img/030.jpg",
        "alt": "Mehrab",
        "w": 480,
        "h": 1378
      },
      {
        "title": "Al-Awalia (QPMC)",
        "tag": "Materials & Public Procurement · Qatar",
        "href": "#/work/case-qpmc",
        "src": "assets/img/031.jpg",
        "alt": "Al-Awalia (QPMC)",
        "w": 480,
        "h": 1648
      },
      {
        "title": "Community College of Qatar",
        "tag": "Higher Education & Self-Service · Qatar",
        "href": "#/work/case-ccq",
        "src": "assets/img/032.jpg",
        "alt": "Community College of Qatar",
        "w": 480,
        "h": 526
      },
      {
        "title": "Surah App",
        "tag": "Qur'an Study & Digital Tafsir · Global",
        "href": "#/work/case-surah",
        "src": "assets/img/033.jpg",
        "alt": "Surah App",
        "w": 480,
        "h": 224
      },
      {
        "title": "Qatar Stars League",
        "tag": "Sports Governance & Financial Compliance · Qatar",
        "href": "#/work/case-qsl",
        "src": "assets/img/034.jpg",
        "alt": "Qatar Stars League",
        "w": 560,
        "h": 315
      },
      {
        "title": "Clayton Art House",
        "tag": "Arts, Crafts & Lifestyle · Alexandria, Egypt",
        "href": "#/work/case-clayton",
        "src": "assets/img/168.jpg",
        "alt": "Clayton Art House",
        "w": 654,
        "h": 805
      }
    ]
  }
] as const;
export const about = {
  "eyebrow": "About",
  "title": "Meet Omnia",
  "bio": "UI/UX Designer with 5+ years turning dense regulatory and organisational requirements from government, public-authority and enterprise clients into interfaces people can actually use — across pensions, higher education, trade compliance, environmental policy, EPC contracting and charitable giving. What I bring to a team: bilingual Arabic/English (RTL/LTR) interface design end-to-end, from user research and journey mapping through wireframes to production-ready design systems — backed by UX certifications from Google, IBM and Meta, and hands-on teaching experience as an Assistant Instructor at Egypt's Information Technology Institute (ITI).",
  "infobar": [
    {
      "k": "Based in",
      "v": "Alexandria, Egypt"
    },
    {
      "k": "Open to",
      "v": "Worldwide · remote & relocation"
    },
    {
      "k": "Experience",
      "v": "5+ years"
    },
    {
      "k": "Focus",
      "v": "Gov & enterprise UI/UX"
    }
  ],
  "skillGroups": [
    {
      "label": "UX / UI Skills",
      "chips": [
        "Design Thinking",
        "User Research",
        "Market Research",
        "User Journey Mapping",
        "Information Architecture",
        "User Personas",
        "Wireframing",
        "Affinity Diagrams",
        "Storyboarding",
        "Design Systems",
        "Empathy Mapping",
        "User Flows",
        "UI Prototyping",
        "Usability Testing",
        "User-Centred Design"
      ]
    },
    {
      "label": "Tools",
      "chips": [
        "Figma",
        "Adobe XD",
        "Photoshop",
        "Illustrator",
        "Zeplin",
        "Miro",
        "Notion",
        "ClickUp",
        "Jira"
      ]
    }
  ],
  "certifications": [
    {
      "name": "7 Levels Of UX Design",
      "issuer": "Google"
    },
    {
      "name": "Designing User Interfaces & Experiences (UI/UX)",
      "issuer": "IBM"
    },
    {
      "name": "Principles of UX/UI Design",
      "issuer": "Meta"
    },
    {
      "name": "The Comprehensive Course in Adobe XD",
      "issuer": "Udemy"
    },
    {
      "name": "Learn Figma Like a Pro, Mixed with UI/UX (2022)",
      "issuer": "Udemy"
    },
    {
      "name": "User Experience Research",
      "issuer": "Edraak"
    },
    {
      "name": "Principles of User Interface Design",
      "issuer": "Edraak"
    },
    {
      "name": "Fundamentals of Interactive Design",
      "issuer": "Edraak"
    },
    {
      "name": "UX Research",
      "issuer": "Edraak"
    }
  ],
  "education": [
    {
      "name": "UI/UX Designer Track",
      "detail": "Information Technology Institute (ITI), MCIT Egypt · Aug – Nov 2022"
    },
    {
      "name": "BA, Faculty of Arts",
      "detail": "Alexandria University · 2016"
    },
    {
      "name": "Assistant Instructor, UI/UX",
      "detail": "Information Technology Institute (ITI), full-time · 2024 – 2025"
    }
  ],
  "recent": [
    {
      "href": "#/work/case-saso",
      "src": "assets/img/156.jpg",
      "alt": "SASO",
      "w": 480,
      "h": 369
    },
    {
      "href": "#/work/case-mcit",
      "src": "assets/img/157.jpg",
      "alt": "MCIT Qatar",
      "w": 480,
      "h": 762
    },
    {
      "href": "#/work/case-joodeskan-kiosk",
      "src": "assets/img/158.jpg",
      "alt": "Jood Eskan Kiosk",
      "w": 480,
      "h": 175
    },
    {
      "href": "#/work/case-qpmc",
      "src": "assets/img/159.jpg",
      "alt": "Al-Awalia (QPMC)",
      "w": 480,
      "h": 1648
    }
  ]
} as const;
export const process = {
  "eyebrow": "Design Process",
  "title": "Process",
  "body": "Three stages, repeated for every government, enterprise and product engagement — from the first stakeholder call to a shipped, tested interface.",
  "steps": [
    {
      "num": "01",
      "title": "Discover & Align",
      "body": "Stakeholder interviews across departments, requirement-gathering with legal and compliance teams, and translating dense regulatory constraints into one shared brief everyone can design against."
    },
    {
      "num": "02",
      "title": "Design & Prototype",
      "body": "Information architecture, wireframes and bilingual (Arabic/English, RTL/LTR) UI, built as reusable design-system components and tested as high-fidelity Figma prototypes before a line of code is written."
    },
    {
      "num": "03",
      "title": "Validate & Ship",
      "body": "Usability testing, structured stakeholder sign-off rounds, developer handoff with full specs, and support through launch — the step most government platforms skip, and the one that saves the relaunch."
    }
  ]
} as const;
export const skills = {
  "eyebrow": "Capabilities",
  "title": "What I Do",
  "body": "End-to-end product design for organisations that can't afford ambiguity — from the first research call to a component library the engineering team can actually ship.",
  "capabilities": [
    {
      "title": "UX Research & Strategy",
      "body": "Stakeholder interviews, journey mapping and requirement synthesis for multi-department government and enterprise platforms."
    },
    {
      "title": "UI Design & Design Systems",
      "body": "Scalable, documented component libraries built to hold up across bilingual Arabic/English products and multiple teams."
    },
    {
      "title": "Government & Enterprise Platforms",
      "body": "Dense, regulation-heavy information architecture made legible and usable for both citizens and internal staff."
    },
    {
      "title": "Prototyping & Handoff",
      "body": "High-fidelity Figma prototypes, developer-ready specs, and hands-on support through QA and launch."
    }
  ],
  "matrixTabs": [
    {
      "cat": "all",
      "label": "All Skills",
      "n": "18"
    },
    {
      "cat": "research",
      "label": "Research & Strategy",
      "n": "8"
    },
    {
      "cat": "ui",
      "label": "UI & Prototyping",
      "n": "5"
    },
    {
      "cat": "systems",
      "label": "Systems & Delivery",
      "n": "3"
    },
    {
      "cat": "specialised",
      "label": "Specialised",
      "n": "2"
    }
  ],
  "matrix": [
    {
      "cat": "research",
      "name": "Design Thinking",
      "body": "Framing an ambiguous, multi-stakeholder brief as a solvable problem before opening a design tool — the entry point on every regulation-heavy engagement."
    },
    {
      "cat": "research",
      "name": "User Research",
      "body": "Structured interviews and contextual inquiry to surface what stakeholders and end-users actually need, not just what they ask for."
    },
    {
      "cat": "research",
      "name": "Market Research",
      "body": "Competitive and category analysis, grounding a product's structure in what similar audiences already expect from comparable platforms."
    },
    {
      "cat": "research",
      "name": "User Journey Mapping",
      "body": "End-to-end maps of a citizen's or employee's path through a service, used to find the drop-off points a redesign should fix first."
    },
    {
      "cat": "research",
      "name": "Information Architecture",
      "body": "Structuring dense, multi-department content into a system a first-time visitor can navigate without a manual — the backbone of every government platform in this portfolio."
    },
    {
      "cat": "research",
      "name": "User Personas",
      "body": "Grounding design decisions in a small set of representative user profiles instead of one imagined “user.”"
    },
    {
      "cat": "research",
      "name": "Affinity Diagrams",
      "body": "Clustering raw research notes and stakeholder input into the themes that actually shape a brief."
    },
    {
      "cat": "research",
      "name": "Empathy Mapping",
      "body": "Separating what a user says from what they do, think and feel, to catch the gap between a stated need and a real one."
    },
    {
      "cat": "ui",
      "name": "Wireframing",
      "body": "Low-fidelity structure first, so stakeholders sign off on layout and flow before a single pixel is styled."
    },
    {
      "cat": "ui",
      "name": "UI Prototyping",
      "body": "High-fidelity, click-through Figma prototypes used for stakeholder walkthroughs and usability testing before development starts."
    },
    {
      "cat": "ui",
      "name": "User Flows",
      "body": "Mapping every path through a form or process — branch points and edge cases included — before it's handed to engineering."
    },
    {
      "cat": "ui",
      "name": "Storyboarding",
      "body": "Sequencing a feature as a short narrative, to pressure-test it against a real use case early in the process."
    },
    {
      "cat": "ui",
      "name": "User-Centred Design",
      "body": "The standard every case study in this portfolio is built on: each decision traced back to a documented user need, not a stakeholder preference."
    },
    {
      "cat": "systems",
      "name": "Design Systems",
      "body": "Documented, reusable component libraries built to hold up across bilingual Arabic/English products and multiple engineering teams."
    },
    {
      "cat": "systems",
      "name": "Usability Testing",
      "body": "Structured testing rounds before launch — the step most government platforms skip, and the one that saves the relaunch."
    },
    {
      "cat": "systems",
      "name": "Dev Handoff",
      "body": "Developer-ready specs and hands-on support through QA, so a shipped product matches the design it started from."
    },
    {
      "cat": "specialised",
      "name": "Bilingual Arabic/English (RTL/LTR)",
      "body": "Full end-to-end interface design in both reading directions — never a mirrored afterthought — across every case study in this portfolio."
    },
    {
      "cat": "specialised",
      "name": "Government & Regulatory UX",
      "body": "Dense, compliance-heavy information architecture made legible for both citizens and internal staff, across seven public-sector clients."
    }
  ],
  "tools": [
    {
      "mono": "Fg",
      "name": "Figma"
    },
    {
      "mono": "Xd",
      "name": "Adobe XD"
    },
    {
      "mono": "Ps",
      "name": "Photoshop"
    },
    {
      "mono": "Ai",
      "name": "Illustrator"
    },
    {
      "mono": "Zp",
      "name": "Zeplin"
    },
    {
      "mono": "Mr",
      "name": "Miro"
    },
    {
      "mono": "Nt",
      "name": "Notion"
    },
    {
      "mono": "Cu",
      "name": "ClickUp"
    },
    {
      "mono": "Ji",
      "name": "Jira"
    }
  ],
  "toolsHead": {
    "title": "Tools & Software",
    "body": "The day-to-day toolkit, from first wireframe to developer-ready handoff."
  },
  "matrixHead": {
    "title": "Skill Matrix",
    "body": "Eighteen working skills across four disciplines — filter by category, or tap any card for how I actually apply it on a live engagement."
  }
} as const;
export const contact = {
  "ctaTitle": "Hiring for a product team? Let's talk.",
  "ctaBody": "Send a message below and it lands in my inbox — or reach me directly:",
  "formHead": {
    "eyebrow": "Send a message",
    "title": "Start a conversation",
    "body": "Fill this in and it’s emailed straight to me — I usually reply within a day. You’ll get a confirmation here once it’s sent, and can open WhatsApp with the same message if you’d rather chat. Or email me directly at Omniaamer835@gmail.com."
  },
  "endpoint": "https://formsubmit.co/Omniaamer835@gmail.com",
  "topics": [
    "A full-time role",
    "A contract / freelance project",
    "A collaboration",
    "Something else"
  ],
  "email": "Omniaamer835@gmail.com",
  "phone": "201558092205",
  "faq": [
    {
      "q": "Are you open to relocating?",
      "a": "Yes — I've been designing for international clients remotely for years, and I'm just as open to relocating when a role calls for it, anywhere in the world."
    },
    {
      "q": "What's your availability / notice period?",
      "a": "Immediately — I'm available to start right away, with no notice period to work around. I take on full-time roles, part-time engagements, and freelance/contract projects alike, and I'm happy to shape the arrangement around what your team needs."
    },
    {
      "q": "Do you design bilingual Arabic/English and RTL interfaces?",
      "a": "Yes — nearly all of my government work ships in Arabic and English side by side, including full RTL layout, typography and component mirroring."
    },
    {
      "q": "What tools do you design in?",
      "a": "Figma for UI and prototyping, with Adobe XD, Photoshop and Illustrator for visual and asset work, and Miro / Notion / Jira for research and cross-team collaboration."
    },
    {
      "q": "Can you work inside an existing design system?",
      "a": "Yes — most of my government engagements involved extending or standardising an existing component library rather than starting from a blank canvas."
    },
    {
      "q": "Remote, on-site, or both?",
      "a": "Both, and in practice, not just on paper. I work fully remote as my default, I'm just as comfortable on-site, and I'm available to travel at any time — so location is never a blocker to getting started."
    }
  ],
  "faqHead": {
    "eyebrow": "FAQ",
    "title": "Answers",
    "body": "Straight answers for hiring managers and recruiters — ask anything else via the contact links below."
  }
} as const;
export const footer = {
  "tagline": "Senior UI/UX Designer based in Alexandria, Egypt — designing government and enterprise digital products, open to opportunities worldwide.",
  "social": [
    {
      "label": "LinkedIn",
      "url": "https://linkedin.com/in/omni-aamer/"
    },
    {
      "label": "Behance",
      "url": "https://behance.net/omnia-amer"
    },
    {
      "label": "Dribbble",
      "url": "https://dribbble.com/Omniaamer"
    }
  ],
  "columns": [
    {
      "title": "Explore",
      "links": [
        {
          "label": "Work",
          "href": "#/work",
          "download": false
        },
        {
          "label": "About",
          "href": "#/about",
          "download": false
        },
        {
          "label": "Process",
          "href": "#/process",
          "download": false
        },
        {
          "label": "Skills",
          "href": "#/skills",
          "download": false
        },
        {
          "label": "Contact",
          "href": "#/contact",
          "download": false
        }
      ]
    },
    {
      "title": "Get in Touch",
      "links": [
        {
          "label": "Omniaamer835@gmail.com",
          "href": "mailto:Omniaamer835@gmail.com",
          "download": false
        },
        {
          "label": "+20 155 809 2205",
          "href": "tel:+201558092205",
          "download": false
        },
        {
          "label": "Download CV",
          "href": "assets/Omnia_Amer_CV_2026.pdf",
          "download": true
        }
      ]
    },
    {
      "title": "Elsewhere",
      "links": [
        {
          "label": "LinkedIn",
          "href": "https://linkedin.com/in/omni-aamer/",
          "download": false
        },
        {
          "label": "Behance",
          "href": "https://behance.net/omnia-amer",
          "download": false
        },
        {
          "label": "Dribbble",
          "href": "https://dribbble.com/Omniaamer",
          "download": false
        }
      ]
    }
  ],
  "copy": "© 2026 Omnia Amer · Senior UI/UX Designer",
  "madeby": "Alexandria, Egypt · Open to relocation worldwide"
} as const;
